### ISSUE TITLE
ERROR  The request could not be satisfied.

### ISSUE THREAD

**Issue by LTheGreats** [rubinius/rubinius.com#62]
When I try to get to the website this is what happens:

ERROR

The request could not be satisfied.

Bad request. 
Generated by cloudfront (CloudFront)
Request ID: B7nvRSJfTBNWEItUU89sG0vXp5fTTCDiTMYTxYDFInZE7P08Xt7ODg==

**Comment by jc00ke** [comment]
I'm seeing this too. @brixen have you made any changes to the S3 bucket or the CF distribution?

**Comment by brixen** [comment]
I've enabled CloudFront and HTTPS using ECM. Initially, I had set CloudFront to HTTPS only. It's now set to redirect and should be working normally. If you are still seeing issues, please try clearing your cache and accessing via https://rubinius.com. If you have issues after that, please re-open or open a new ticket.
